version: "3"
services:

  proxy:
    image: docker.io/kalise/http-proxy-server:latest
    ports:
      - "80:80"
    environment:
      REMOTE_PORT: 8080
      REMOTE_SERVER: nodejs
    networks:
      - application_network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: pause
        max_failure_ratio: 0
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

  nodejs:
    image: docker.io/kalise/nodejs-web-app:latest
    environment:
      MESSAGE: 'Hello Docker Swarm'
    networks:
      - application_network
    volumes:
      - log-volume:/var/log
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: pause
        max_failure_ratio: 0
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

volumes:
  log-volume:
    driver: local

networks:
  application_network:
    driver: overlay
    driver_opts:
      com.docker.network.driver.overlay.vxlanid_list: 9000
    ipam:
     driver: default
     config:
       - subnet: 172.128.1.0/24
